###### Application Specific ######
dataset: 'CIFAR10' # options: CIFAR100, CIFAR10, ImageNet
network: 'ConvNeXtTiny' # AlexNet, DenseNet201, DenseNet169, DenseNet161, DenseNet121, GoogLeNet
# InceptionV3, MNASNet_0_5, MNASNet_0_75, MNASNet_1, MNASNet_1_3, MobileNetV2, ResNet18
# ResNet34, ResNet50, ResNet101, ResNet152, ResNext50, ResNext101, WideResNet50, WideResNet101
# ShuffleNetV2_0_5, ShuffleNetV2_1, ShuffleNetV2_1_5, ShuffleNetV2_2, SqueezeNet_1,
# SqueezeNet_1_1, VGG11, VGG11_BN, VGG13, VGG13_BN, VGG16, VGG16_BN, VGG19, VGG19_BN,
# EfficientNetB4
# ResNet101CIFAR, ResNet50CIFAR, ResNet34CIFAR, ResNet18CIFAR, ResNeXtCIFAR, EfficientNetB0CIFAR, VGG16CIFAR, DenseNet121CIFAR
optimizer: 'RMSGD' # options: SGD, AdaM, AdaGrad, RMSProp, AdaDelta
scheduler: 'None' # options: RMSGD, StepLR, CosineAnnealingWarmRestarts, OneCycleLR


###### Suggested Tune ######
init_lr: 0.03
early_stop_threshold: -1 # set to -1 if you wish not to use early stop, or equally, set to a high value. Set to -1 if not using RMSGD
optimizer_kwargs:
  momentum: 0.9
  weight_decay: 1e-4
  beta: 0.98
  linear: False
  gamma: 0.98
  step_size: 1
scheduler_kwargs: {}
cutout: False
n_holes: 1
cutout_length: 16

###### Suggested Default ######
p: 1 # options: 1, 2.
n_trials: 1
num_workers: 16
max_epochs: 250
mini_batch_size: 128
loss: 'cross_entropy' # options: cross_entropy
early_stop_patience: 10 # epoch window to consider when deciding whether to stop
